### ISSUE TITLE
Horrible chat lag when checking if chat messages are passwords

### ISSUE THREAD

**Issue by DaPigGuy** [DaPigGuy/PiggyAuth#56] opened 2017-04-16 16:06 UTC
# DO NOT REMOVE THIS
Please make sure your issue complies with these guidelines:
- * [x] Be using PMMP
- * [x] Make sure the issue hasn't already been reported
- * [x] Make sure you are on the latest version of PMMP & PiggyAuth
- * [x] Have a detailed title like "Players are being kicked randomly"
- * [x] Provide any crash dumps or errors

#### **General**
 
When players chat, there is horrible lag when checking if messages are the password. (Currently removed from PiggyAuth)

#### **Server Software:**
 PMMP

#### **Version of PiggyAuth:**
 3.0.0.10

#### **Data Provider:**

- [x] MySQL
- [ ] SQLite

#### **Steps to Reproduce the Issue**

1. Chat a lot

**Comment by AnUnknownPerson** [comment] 2017-04-28 23:28
Were in the code is it set to check for passwords?

**Comment by DaPigGuy** [comment] 2017-04-28 23:38
EventListener

**Comment by AnUnknownPerson** [comment] 2017-05-02 22:50
Show me the code were it checks please.

**Comment by DaPigGuy** [comment] 2017-05-03 00:27
EventListener Line 194

**Comment by AnUnknownPerson** [comment] 2017-05-04 04:16
OK let me see

**Comment by Fabiansigala** [comment] 2017-05-04 04:19
It should work fine

**Comment by AnUnknownPerson** [comment] 2017-05-04 04:20
What test server are you using?
1 how are you hosting?
2 how Much ram do you have
3 how Much ram have you used?
4 what plugins are installed?

**Comment by Thunder33345** [comment] 2017-05-04 07:23
it probably the same regardless of details like ram etc, since you are querying not via async

**Comment by Aericio** [comment] 2017-05-05 02:26
That shouldn't matter, you can have a server with one player and you can notice it.

**Comment by AnUnknownPerson** [comment] 2017-05-05 22:00
@MCPEPIG @Aericio @Thunder33345 hmm can I see a video or a clip of it!?

**Comment by AnUnknownPerson** [comment] 2017-05-05 22:02
@MCPEPIG @Thunder33345 @Aericio us there any error or spam in the console?

**Comment by Aericio** [comment] 2017-05-06 02:58
Me and @MCPEPIG already tested & confirmed this bug... there are no errors.

**Comment by DaPigGuy** [comment] 2017-05-06 05:40
Confirmed by 3 people on 3 different servers using PiggyAuth.

**Comment by AnUnknownPerson** [comment] 2017-05-06 16:56
Hmm ok

**Comment by SleepSpace9** [comment] 2017-05-06 18:56
I agree to @Thunder33345 that is has to be done via async. To compare chat message and password it has to be generated a hash, which is almost done extra slow for security reasons. 
(https://github.com/MCPEPIG/PiggyAuth/blob/master/src/PiggyAuth/Main.php#L240)
But also via async there would probably be a noticeable delay before it sends the message. I'm really unsure if there is a secure solution for this issue.

**Comment by Thunder33345** [comment] 2017-05-06 20:30
just include an option to not check it for now some owners dont really think this is a necessary feature at the price of speed, also how hereauth did it?

and other plugins who does anti share pwd things??

**Comment by SleepSpace9** [comment] 2017-05-06 23:04
I think other plugins are using weaker hash algorithms so they are more easy to brute-force.
HereAuth and SimpleAuth are using a combination of salted SHA-512 and Whirlpool hash.
PiggyAuth is using BCrypt which is designed to make it hard to brute-force.
You could try reducing the **cost** value in config.yml which should also reduce the amount of time to compute: https://github.com/MCPEPIG/PiggyAuth/blob/master/resources/config.yml#L166

**Comment by SalmonDE** [comment] 2017-05-27 11:44
Is this really only related to chat messages? I'm experiencing a lag spike [here](https://github.com/MCPEPIG/PiggyAuth/blob/master/src/PiggyAuth/Main.php#L256) when a player uses /login.

**Comment by SalmonDE** [comment] 2017-05-27 21:55
I believe this is fixed in #76

**Closed as completed** 2017-05-27 21:57 UTC
Labels: bug, fixed/done
